In [86]:
# Import library numpy, pandas dan scikit-learn
import numpy as np
import pandas as pd
from sklearn import tree

print("Import berhasil")

Import berhasil

In [87]:
# Membaca Dataset dari File ke Pandas DataFrame
irisDataset = pd.read_csv('Dataset Iris.csv', delimiter=';', header=0)

print(irisDataset.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0   1           7.00          3.02           4.07          1.04
1   2           6.04          3.02           4.05          1.05
2   3           6.09          3.01           4.09          1.05
3   4           5.05          2.03           4.00          1.03
4   5           6.05          2.08           4.06          1.05

           Species
0  Iris-versicolor
1  Iris-versicolor
2  Iris-versicolor
3  Iris-versicolor
4  Iris-versicolor

In [88]:
print(irisDataset.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             100 non-null    int64
 1   SepalLengthCm  100 non-null    float64
 2   SepalWidthCm   100 non-null    float64
 3   PetalLengthCm  100 non-null    float64
 4   PetalWidthCm   100 non-null    float64
 5   Species        100 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 4.8 KB
None

In [89]:
# Cek data secara ringkas
print(irisDataset.head())
print("\nKolom dataset:", irisDataset.columns)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0   1           7.00          3.02           4.07          1.04
1   2           6.04          3.02           4.05          1.05
2   3           6.09          3.01           4.09          1.05
3   4           5.05          2.03           4.00          1.03
4   5           6.05          2.08           4.06          1.05

           Species
0  Iris-versicolor
1  Iris-versicolor
2  Iris-versicolor
3  Iris-versicolor
4  Iris-versicolor

Kolom dataset: Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='str')

In [90]:
# Mengubah kelas (kolom "Species") dari String ke Unique-Integer
irisDataset["Species"] = pd.factorize(irisDataset["Species"])[0]

print(irisDataset.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1           7.00          3.02           4.07          1.04        0
1   2           6.04          3.02           4.05          1.05        0
2   3           6.09          3.01           4.09          1.05        0
3   4           5.05          2.03           4.00          1.03        0
4   5           6.05          2.08           4.06          1.05        0

In [91]:
irisDataset.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1           7.00          3.02           4.07          1.04        0
1   2           6.04          3.02           4.05          1.05        0
2   3           6.09          3.01           4.09          1.05        0
3   4           5.05          2.03           4.00          1.03        0
4   5           6.05          2.08           4.06          1.05        0

In [92]:
from sklearn.model_selection import train_test_split

In [93]:
# Hapus kolom Id kalau ada (biar gak error)
irisDataset = irisDataset.drop(columns=[col for col in ["Id"] if col in irisDataset.columns])

print(irisDataset.head())

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0           7.00          3.02           4.07          1.04        0
1           6.04          3.02           4.05          1.05        0
2           6.09          3.01           4.09          1.05        0
3           5.05          2.03           4.00          1.03        0
4           6.05          2.08           4.06          1.05        0

In [94]:
print(irisDataset.columns)

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='str')

In [95]:
irisDataset

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            7.00          3.02           4.07          1.04        0
1            6.04          3.02           4.05          1.05        0
2            6.09          3.01           4.09          1.05        0
3            5.05          2.03           4.00          1.03        0
4            6.05          2.08           4.06          1.05        0
..            ...           ...            ...           ...      ...
95           6.07          3.00           5.02          2.03        1
96           6.03          2.05           5.00          1.09        1
97           6.05          3.00           5.02          2.00        1
98           6.02          3.04           5.04          2.03        1
99           5.09          3.00           5.01          1.08        1

[100 rows x 5 columns]

In [96]:
# Mengubah DataFrame ke array NumPy
irisDataset = irisDataset.to_numpy()

print(type(irisDataset))
print(irisDataset[:5])

<class 'numpy.ndarray'>
[[7.   3.02 4.07 1.04 0.  ]
 [6.04 3.02 4.05 1.05 0.  ]
 [6.09 3.01 4.09 1.05 0.  ]
 [5.05 2.03 4.   1.03 0.  ]
 [6.05 2.08 4.06 1.05 0.  ]]

In [97]:
# Membagi Dataset => 80 training, 20 testing (manual split)
dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]), axis=0)
dataTesting = np.concatenate((irisDataset[40:50, :], irisDataset[90:100, :]), axis=0)

print("Data training shape:", dataTraining.shape)
print("Data testing shape:", dataTesting.shape)

Data training shape: (80, 5)
Data testing shape: (20, 5)

In [98]:
from sklearn.model_selection import train_test_split

In [99]:
# Memecah Dataset ke Input dan Label
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]

print("Shape inputTraining:", inputTraining.shape)
print("Shape inputTesting:", inputTesting.shape)
print("Shape labelTraining:", labelTraining.shape)
print("Shape labelTesting:", labelTesting.shape)

Shape inputTraining: (80, 4)
Shape inputTesting: (20, 4)
Shape labelTraining: (80,)
Shape labelTesting: (20,)

In [100]:
print(inputTesting)

[[5.05 2.06 4.04 1.02]
 [6.01 3.   4.06 1.04]
 [5.08 2.06 4.   1.02]
 [5.   2.03 3.03 1.  ]
 [5.06 2.07 4.02 1.03]
 [5.07 3.   4.02 1.02]
 [5.07 2.09 4.02 1.03]
 [6.02 2.09 4.03 1.03]
 [5.01 2.05 3.   1.01]
 [5.07 2.08 4.01 1.03]
 [6.07 3.01 5.06 2.04]
 [6.09 3.01 5.01 2.03]
 [5.08 2.07 5.01 1.09]
 [6.08 3.02 5.09 2.03]
 [6.07 3.03 5.07 2.05]
 [6.07 3.   5.02 2.03]
 [6.03 2.05 5.   1.09]
 [6.05 3.   5.02 2.  ]
 [6.02 3.04 5.04 2.03]
 [5.09 3.   5.01 1.08]]

In [101]:
print(inputTesting.shape)

(20, 4)

In [102]:
# Mendefinisikan Decision Tree Classifier
model = tree.DecisionTreeClassifier()

print(model)

DecisionTreeClassifier()

In [103]:
# Mentraining Model
model = model.fit(inputTraining, labelTraining)

print("Model berhasil dilatih")

Model berhasil dilatih

In [104]:
hasilPrediksi = model.predict(inputTesting)
print(hasilPrediksi)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

In [105]:
# Perbandingan Hasil
print("\nPerbandingan (Asli vs Prediksi):")
for i in range(len(labelTesting)):
    print(f"Data ke-{i+1}: Asli={labelTesting[i]}, Prediksi={hasilPrediksi[i]}")

Perbandingan (Asli vs Prediksi):
Data ke-1: Asli=0.0, Prediksi=0.0
Data ke-2: Asli=0.0, Prediksi=0.0
Data ke-3: Asli=0.0, Prediksi=0.0
Data ke-4: Asli=0.0, Prediksi=0.0
Data ke-5: Asli=0.0, Prediksi=0.0
Data ke-6: Asli=0.0, Prediksi=0.0
Data ke-7: Asli=0.0, Prediksi=0.0
Data ke-8: Asli=0.0, Prediksi=0.0
Data ke-9: Asli=0.0, Prediksi=0.0
Data ke-10: Asli=0.0, Prediksi=0.0
Data ke-11: Asli=1.0, Prediksi=1.0
Data ke-12: Asli=1.0, Prediksi=1.0
Data ke-13: Asli=1.0, Prediksi=1.0
Data ke-14: Asli=1.0, Prediksi=1.0
Data ke-15: Asli=1.0, Prediksi=1.0
Data ke-16: Asli=1.0, Prediksi=1.0
Data ke-17: Asli=1.0, Prediksi=1.0
Data ke-18: Asli=1.0, Prediksi=1.0
Data ke-19: Asli=1.0, Prediksi=1.0
Data ke-20: Asli=1.0, Prediksi=1.0

In [106]:
# Memprediksi Input Data Testing
hasilPrediksi = model.predict(inputTesting)

print("Label Sebenarnya :", labelTesting)
print("Hasil Prediksi   :", hasilPrediksi)

# Tambahan cek sederhana
print("Jumlah data test :", len(labelTesting))

Label Sebenarnya : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Hasil Prediksi   : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Jumlah data test : 20

In [107]:
from sklearn.metrics import accuracy_score
print("Akurasi:", accuracy_score(labelTesting, hasilPrediksi))

Akurasi: 1.0

In [108]:
# Menghitung Akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()

total = prediksiBenar + prediksiSalah

print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", round((prediksiBenar / total) * 100, 2), "%")

Prediksi Benar : 20 data
Prediksi Salah : 0 data
Akurasi : 100.0 %

In [109]:
# Kesimpulan Akurasi
akurasi = prediksiBenar / (prediksiBenar + prediksiSalah) * 100

print("\nKesimpulan:")
print(f"Model memiliki tingkat akurasi sebesar {round(akurasi, 2)}%")
print("Model cukup baik untuk klasifikasi dataset Iris.")

Kesimpulan:
Model memiliki tingkat akurasi sebesar 100.0%
Model cukup baik untuk klasifikasi dataset Iris.